/*
  Copyright (c) 2014-2015 Arduino LLC.  All right reserved.

  This library is free software; you can redistribute it and/or
  modify it under the terms of the GNU Lesser General Public
  License as published by the Free Software Foundation; either
  version 2.1 of the License, or (at your option) any later version.

  This library is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
  See the GNU Lesser General Public License for more details.

  You should have received a copy of the GNU Lesser General Public
  License along with this library; if not, write to the Free Software
  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
*/

#include "variant.h"
#include "Arduino.h"

/*
 * Pins descriptions
 */

//TCC0 IOSET 6
//TCC1 IOSET 1
//TC0 IOSET 1
//TC1 IOSET 1
//TC2 IOSET 2
//TC3 IOSET 1
//TC4 IOSET 1
const PinDescription g_APinDescription[PINS_COUNT]=
{
  { PORTB, 8, PIO_SERCOM, PIN_ATTR_PWM, No_ADC_Channel, TC4_CH0, NOT_ON_TIMER, EXTERNAL_INT_8 },       // D0 TX:  SERCOM4/PAD[0]
  { PORTB, 9, PIO_SERCOM, PIN_ATTR_PWM, No_ADC_Channel, TC4_CH1, NOT_ON_TIMER, EXTERNAL_INT_9 },       // D1 RX:  SERCOM4/PAD[1]
  { PORTA, 16, PIO_SERCOM, PIN_ATTR_PWM, No_ADC_Channel, TC2_CH0, TCC1_CH0, EXTERNAL_INT_0},           // D2 SDA:  SERCOM1/PAD[0]
  { PORTA, 17, PIO_SERCOM, PIN_ATTR_PWM, No_ADC_Channel, TC2_CH1, TCC1_CH1, EXTERNAL_INT_1},           // D3 SCL:  SERCOM1/PAD[1]
  { PORTB, 0, PIO_SERCOM, PIN_ATTR_DIGITAL, No_ADC_Channel, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_0}, // D4 MISO: SERCOM5/PAD[2]
  { PORTB, 2, PIO_SERCOM, PIN_ATTR_DIGITAL, No_ADC_Channel, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_2}, // D5 CS:   SERCOM5/PAD[0]
  { PORTB, 3, PIO_SERCOM, PIN_ATTR_DIGITAL, No_ADC_Channel, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_3}, // D8 MOSI: SERCOM5/PAD[1]
  { PORTB, 1, PIO_SERCOM, PIN_ATTR_DIGITAL, No_ADC_Channel, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_1}, // D9 SCK:  SERCOM5/PAD[3]
  { PORTB, 16, PIO_DIGITAL, PIN_ATTR_PWM, No_ADC_Channel, TC6_CH0, TCC0_CH4, EXTERNAL_INT_0},          // D6
  { PORTA, 20, PIO_DIGITAL, PIN_ATTR_PWM, No_ADC_Channel, TC7_CH0, TCC0_CH0, EXTERNAL_INT_4},          // D7
  { PORTA, 21, PIO_DIGITAL, PIN_ATTR_PWM, No_ADC_Channel, TC7_CH1, TCC1_CH5, EXTERNAL_INT_5},          // D10
  { PORTA, 22, PIO_DIGITAL, PIN_ATTR_PWM, No_ADC_Channel, TC4_CH0, TCC1_CH6, EXTERNAL_INT_6},          // D11
  { PORTB, 12, PIO_DIGITAL, PIN_ATTR_PWM, No_ADC_Channel, TC4_CH0, NOT_ON_TIMER, EXTERNAL_INT_12},     // D12
  { PORTB, 31, PIO_DIGITAL, PIN_ATTR_PWM, No_ADC_Channel, TC0_CH1, TCC0_CH6, EXTERNAL_INT_15},         // D13
  { PORTB, 17, PIO_DIGITAL, PIN_ATTR_PWM, No_ADC_Channel, TC6_CH1, NOT_ON_TIMER, EXTERNAL_INT_NONE},    // D14
  { PORTB, 13, PIO_DIGITAL, PIN_ATTR_PWM, No_ADC_Channel, TC4_CH1, TCC3_CH1, EXTERNAL_INT_13},         // D15
  { PORTB, 23, PIO_DIGITAL, PIN_ATTR_PWM, No_ADC_Channel, TC7_CH1, NOT_ON_TIMER, EXTERNAL_INT_7},      // D16
  { PORTB, 22, PIO_DIGITAL, PIN_ATTR_PWM, No_ADC_Channel, TC7_CH0, NOT_ON_TIMER, EXTERNAL_INT_6},      // D17
  { PORTB, 4, PIO_ANALOG, PIN_ATTR_ANALOG | PIN_ATTR_PWM, ADC_Channel7, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_4},    // D18
  { PORTB, 5, PIO_ANALOG, PIN_ATTR_ANALOG | PIN_ATTR_PWM, ADC_channel14, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_5},    // D19
  { PORTA, 14, PIO_DIGITAL, PIN_ATTR_PWM, No_ADC_Channel, TC3_CH0, NOT_ON_TIMER, EXTERNAL_INT_14},     // D20
  { PORTA, 15, PIO_DIGITAL, PIN_ATTR_PWM, No_ADC_Channel, TC3_CH1, NOT_ON_TIMER, EXTERNAL_INT_15},     // D21
  { PORTA, 4, PIO_ANALOG, PIN_ATTR_ANALOG | PIN_ATTR_PWM, ADC_Channel4, TC0_CH0, NOT_ON_TIMER, EXTERNAL_INT_4},       // D22
  { PORTA, 5, PIO_ANALOG, PIN_ATTR_ANALOG | PIN_ATTR_PWM, ADC_Channel5, TC0_CH1, NOT_ON_TIMER, EXTERNAL_INT_5},       // D23
  { PORTA, 12, PIO_DIGITAL, PIN_ATTR_PWM, No_ADC_Channel, TC2_CH0, NOT_ON_TIMER, EXTERNAL_INT_12},     // D24
  { PORTA, 13, PIO_DIGITAL, PIN_ATTR_PWM, No_ADC_Channel, TC2_CH1, NOT_ON_TIMER, EXTERNAL_INT_13},     // D25
  { PORTA, 18, PIO_DIGITAL, PIN_ATTR_PWM, No_ADC_Channel, TC3_CH0, NOT_ON_TIMER, EXTERNAL_INT_2},      // D26
  { PORTA, 19, PIO_DIGITAL, PIN_ATTR_PWM, No_ADC_Channel, TC3_CH1, NOT_ON_TIMER, EXTERNAL_INT_3},      // D27
  { PORTA, 2, PIO_ANALOG, PIN_ATTR_ANALOG | PIN_ATTR_PWM, ADC_Channel0, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_2},    // D28
  { PORTA, 23, PIO_DIGITAL, PIN_ATTR_PWM, No_ADC_Channel, TC4_CH1, TCC1_CH6, EXTERNAL_INT_7},          // D29

  { PORTB, 6, PIO_DIGITAL, PIN_ATTR_DIGITAL, No_ADC_Channel, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_NONE},          // NEOPIXEL


  { PORTA, 24, PIO_COM, PIN_ATTR_NONE, No_ADC_Channel, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_NONE }, // USB/DM
  { PORTA, 25, PIO_COM, PIN_ATTR_NONE, No_ADC_Channel, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_NONE }, // USB/DP

  { PORTA, 3, PIO_ANALOG, PIN_ATTR_ANALOG, No_ADC_Channel, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_NONE }, // DAC/VREFP

  { PORTA,  2, PIO_ANALOG, PIN_ATTR_ANALOG, DAC_Channel0, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_NONE }, // DAC/VOUT0
  { PORTA,  5, PIO_ANALOG, PIN_ATTR_ANALOG, DAC_Channel1, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_NONE }, // DAC/VOUT1

  { PORTB, 10, PIO_COM, PIN_ATTR_NONE, No_ADC_Channel, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_NONE }, //QSCK
  { PORTB, 11, PIO_COM, PIN_ATTR_NONE, No_ADC_Channel, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_NONE }, //QCS
  { PORTA, 8, PIO_COM, PIN_ATTR_NONE, No_ADC_Channel, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_NONE }, //QD0
  { PORTA, 9, PIO_COM, PIN_ATTR_NONE, No_ADC_Channel, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_NONE }, //QD1
  { PORTA, 10, PIO_COM, PIN_ATTR_NONE, No_ADC_Channel, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_NONE }, //QD2
  { PORTA, 11, PIO_COM, PIN_ATTR_NONE, No_ADC_Channel, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_NONE }, //QD3

  { PORTA, 27, PIO_DIGITAL, PIN_ATTR_NONE, No_ADC_Channel, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_NONE }, // CAN S
  { PORTB, 14, PIO_COM, PIN_ATTR_NONE, No_ADC_Channel, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_NONE }, // CAN TX
  { PORTB, 15, PIO_COM, PIN_ATTR_NONE, No_ADC_Channel, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_NONE }, // CAN RX
} ;

const void* g_apTCInstances[TCC_INST_NUM+TC_INST_NUM]={ TCC0, TCC1, TCC2, TCC3, TCC4, TC0, TC1, TC2, TC3, TC4, TC5 } ;
const uint32_t GCLK_CLKCTRL_IDs[TCC_INST_NUM+TC_INST_NUM] = { TCC0_GCLK_ID, TCC1_GCLK_ID, TCC2_GCLK_ID, TCC3_GCLK_ID, TCC4_GCLK_ID, TC0_GCLK_ID, TC1_GCLK_ID, TC2_GCLK_ID, TC3_GCLK_ID, TC4_GCLK_ID, TC5_GCLK_ID } ;

// Multi-serial objects instantiation
SERCOM sercom0( SERCOM0 ) ;
SERCOM sercom1( SERCOM1 ) ;
SERCOM sercom2( SERCOM2 ) ;
SERCOM sercom3( SERCOM3 ) ;
SERCOM sercom4( SERCOM4 ) ;
SERCOM sercom5( SERCOM5 ) ;

Uart Serial1( &sercom5, PIN_SERIAL1_RX, PIN_SERIAL1_TX, PAD_SERIAL1_RX, PAD_SERIAL1_TX ) ;

void SERCOM5_0_Handler()
{
  Serial1.IrqHandler();
}
void SERCOM5_1_Handler()
{
  Serial1.IrqHandler();
}
void SERCOM5_2_Handler()
{
  Serial1.IrqHandler();
}
void SERCOM5_3_Handler()
{
  Serial1.IrqHandler();
}

void initVariant(void);
